global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#general'
