version: '3'
services:

  zipkin:
    image: openzipkin/zipkin
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "9411:9411"
    networks:
      - reddit


  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - reddit

  elasticsearch:
    image: elasticsearch:7.4.0
    expose:
      - 9200
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - node.master=true
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - reddit

  kibana:
    image: kibana:7.4.0
    ports:
      - "5601:5601"
    networks:
      - reddit
networks:
  reddit:
