{
 "title": "UI_Service_Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP response time 95th",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(ui_request_count[5m])) by (le))"
    }
   ]
  },
  {
   "title": "UI HTTP request",
   "type": "graph",
   "description": "all http request",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ui_request_count" }
   ]
  },
  {
   "title": "Rate of UI http reqests with Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])"
    }
   ]
  }
 ]
}