version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${VERSION}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - fron_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${VERSION}
    networks:
      - back_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${VERSION}
    networks:
      - back_net

volumes:
  post_db:

networks:
  fron_net:

  back_net:
